config/routes.rb
Rails.application.routes.draw do
  resources :members
  resources :restaurantes
  devise_for :users, controllers: {
    confirmations: 'confirmations'
  }
  root 'pages#home'

  get 'pages/dashboard'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :restaurante
end

app/models/memeber.rb
class Memeber < ApplicationRecord
  belongs_to :user
  belongs_to :restaurante
end

app/models/restaurante.rb
class Restaurante < ApplicationRecord
    validates :name, presence: true

    has_many  :members
    has_many  :users, through: :members

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many  :members
  has_many  :restaurantes, through: :members

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
 
    private
        def after_confirmation_path_for(resource_name, resource)
            sign_in(resource)
            pages_dashboard_path
        end

end           

app/controllers/members_controller.rb
class MembersController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]
  
  def home
  end

  def dashboar
   
  end
end

app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
  before_action :set_restaurante, only: %i[ show edit update destroy ]
  before_action :authorize_member, only: %i[ show edit update destroy ]


  # GET /restaurantes or /restaurantes.json
  def index
    @restaurantes = current_user.restaurantes
  end

  # GET /restaurantes/1 or /restaurantes/1.json
  def show    
  end

  # GET /restaurantes/new
  def new
    @restaurante = Restaurante.new
  end

  # GET /restaurantes/1/edit
  def edit
  end

  # POST /restaurantes or /restaurantes.json
  def create
    @restaurante = Restaurante.new(restaurante_params)
    respond_to do |format|
      if @restaurante.save
        @restaurante.members.create(user: current_user, rte_roles: {rte_admin: true})
        format.html { redirect_to restaurante_url(@restaurante), notice: "Restaurante was successfully created." }
        format.json { render :show, status: :created, location: @restaurante }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurantes/1 or /restaurantes/1.json
  def update
    respond_to do |format|
      if @restaurante.update(restaurante_params)
        format.html { redirect_to restaurante_url(@restaurante), notice: "Restaurante was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurante }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurantes/1 or /restaurantes/1.json
  def destroy
    @restaurante.destroy!

    respond_to do |format|
      format.html { redirect_to restaurantes_url, notice: "Restaurante was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def authorize_member
      return redirect_to root_path, alert: 'No eres miembro de este Restaurante' unless @restaurante.users.include? current_user
    end 
    def set_restaurante
      @restaurante = Restaurante.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurante_params
      params.require(:restaurante).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/memebers_helper.rb
module MemebersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurantes_helper.rb
module RestaurantesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "shared/header" %>
    <%= render "shared/flashes" %>
    <%#= render "shared/navbar2" %>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1>Dashboard</h1>
<h3><%= current_user.email %></>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/restaurantes/_form.html.erb
<%= form_with(model: restaurante) do |form| %>
  <% if restaurante.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(restaurante.errors.count, "error") %> prohibited this restaurante from being saved:</h2>

      <ul>
        <% restaurante.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurantes/_restaurante.html.erb
<div id="<%= dom_id restaurante %>">
  <p>
    <strong>Name:</strong>
    <%= restaurante.name %>
  </p>

</div>

app/views/restaurantes/edit.html.erb
<h1>Editing restaurante</h1>

<%= render "form", restaurante: @restaurante %>

<br>

<div>
  <%= link_to "Show this restaurante", @restaurante %> |
  <%= link_to "Back to restaurantes", restaurantes_path %>
</div>

app/views/restaurantes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Restaurantes</h1>

<div id="restaurantes">
  <% @restaurantes.each do |restaurante| %>
    <%= render restaurante %>
    <p>
      <%= link_to "Show this restaurante", restaurante %>
    </p>
  <% end %>
</div>

<%= link_to "New restaurante", new_restaurante_path %>

app/views/restaurantes/new.html.erb
<h1>New restaurante</h1>

<%= render "form", restaurante: @restaurante %>

<br>

<div>
  <%= link_to "Back to restaurantes", restaurantes_path %>
</div>

app/views/restaurantes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @restaurante %>

<div>
  <%= link_to "Edit this restaurante", edit_restaurante_path(@restaurante) %> |
  <%= link_to "Back to restaurantes", restaurantes_path %>

  <%= button_to "Destroy this restaurante", @restaurante, method: :delete %>
</div>

app/views/shared/_flashes.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible d-flex justify-content-center contated-notice" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% elsif alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <!--a class="nav-link active" aria-current="page" href="#">Home</a-->
          <%= link_to 'Home', root_path, class: "nav-link #{yield(:home_active)}" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Restaurantes', restaurantes_path, class: "nav-link #{yield(:restaurantes_active)}" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Dashboard', pages_dashboard_path, class: "nav-link #{yield(:pages_dashboard_active)}" %>
          </li>
          <!-- Dropdown -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.email%>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Edit User', edit_user_registration_path, class: "dropdown-item #{yield(:edit_user_active)}" %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete,class: "dropdown-item" %>
            </div>
          </li>
          <!-- Dropdown -->
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sing up', new_user_registration_path, class: "nav-link #{yield(:sign_up_active)}" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sing in', new_user_session_path, class: "nav-link #{yield(:sign_in_active)}" %>
          </li>
        <% end %>
      </div>
    </div>
  </nav>

app/views/shared/_navbar2.html.erb
<% if current_page?(root_path) %>
  <nav class="navbar navbar-expand-md home-navbar navbar-dark "> 
<% else %>
  <nav class="navbar navbar-expand-md navbar-others navbar-dark "> <%#<nav class="navbar-expand-md will expand from medium screen size up %>
<% end %>

<%# Brand %>
<a class = 'navbar-brand' href='/'>Listis</a>
<%# Toggle button %>
  <button class="navbar-toggler navbar-toggler-right custom-toggler " type="button" data-toggle="collapse" data-target="#collapsingnavbar" aria-controls="collapsingnavbar" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <div class="collapse navbar-collapse" id="collapsingnavbar">
      <ul class="navbar-nav mr-auto"> <!--DONE TO PLACE THE SIGNS INSIDE THE DROP DOWN-->
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link #{yield(:home_active)}" %>  <!--pages_home_path -->
        </li>
        <li class="nav-item">
          <%#= link_to 'Contact', new_form_message_path, class: "nav-link #{yield(:contact_active)}" %>
        </li>        
        <li class="nav-item">
          <%#= link_to 'Improvements', improvements_path, class: "nav-link #{yield(:improvements_active)}" %>
         </li><% if user_signed_in? %>
          <li class="nav-item">
            <%#= link_to 'My Lists', lists_path, class: "nav-link #{yield(:list_active)}" %>
          </li>
        <% end %>
      <!--< /ul> -->
     
      
<!-- <div class="d-flex justify-content-end" >  -->          
      <% if user_signed_in? %>
<!-- Dropdown -->
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if !current_user.first_name.blank? %>    
            <%= current_user.first_name%>      
          <% else %>
            <%= current_user.email%> 
          <% end %> 
          <%#= render 'navbar_usersigned_in_logic', current_user: current_use CHECK HOW TO MOVE IT TO A PARTIAL%>
        </a>      
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Edit User', edit_user_registration_path, class: "nav-link #{yield(:edit_user_active)}" %>
           <%= link_to "Logout", destroy_user_session_path, method: :delete,class: "nav-link" %>
        </div>
      </li>
<!-- Dropdown -->         
      <% else %>
           <li class="nav-item">
         <%= link_to 'Sing up', new_user_registration_path, class: "nav-link #{yield(:sign_up_active)}" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sing in', new_user_session_path, class: "nav-link #{yield(:sign_in_active)}" %>
        </li>
      <% end %>  
      </ul>        
    </div>      
</nav>